### PR TITLE
bootstrapper only annotation

### PR DESCRIPTION
**Pull request by tiagoposse**
### Description

Add annotation to stop injection of renewer, this is useful when you want to execute a job. If the renewer is injected, it will not stop running causing the job not to finish.

### CODE REVIEW

**Comment by tiagoposse** [comment]
@maraino Any new on this :) ?
I just rebased and was hoping this could be added to the next release. If you need any other info /change from me let me know. Thanks!

**Comment by dopey** [comment]
@tiagoposse Are you able to sign the CLA? I think the PR looks good.

**Review by maraino — APPROVED** [review]
@dopey @tiagoposse lgtm

**Comment by dopey** [comment]
Hey @tiagoposse we're ready to merge this on our end, but for legal reasons we need you all contributors to sign the CLA. Let us know if that's an issue for you and we can figure out how to move forwards.

**Comment by tiagoposse** [comment]
Hey! Looks like this got lost in space and time on my end. If you reopen, I'll sign the CLA so we can get this merged.

**Pull request closed without merging**
