### PR TITLE
Convert to Go Modules

### LINKED ISSUE #6: Move `autocert` to go modules

### LINKED ISSUE #8: Autocert can't be built since certificates >0.10.0 and cli>0.10.0
### Subject of the issue
Trying to build autocert leads to a lot of issues : 
* We encounter a  [known issue ](https://github.com/russross/blackfriday#known-issue-with-dep) between blackfriday and dep. This can be fixed by adding an override in Gopkg.toml to force blackfriday 1.5.2 and run dep ensure -update
* We then get an issue compiling nosql/badger. No clue what's going on here, only way to move forward was to remove all references to badger from github.com/smallstep/nosql/nosql.go : 
```
badger/badger.go:27:4: bo.Dir undefined (type func(string) badger.Options has no field or method Dir)
badger/badger.go:29:5: bo.ValueDir undefined (type func(string) badger.Options has no field or method ValueDir)
badger/badger.go:31:5: bo.ValueDir undefined (type func(string) badger.Options has no field or method ValueDir)
badger/badger.go:34:26: cannot use bo (type func(string) badger.Options) as type badger.Options in argument to badger.Open
badger/badger.go:122:12: assignment mismatch: 2 variables but 1 values
badger/badger.go:122:25: not enough arguments in call to item.Value
        have ()
        want (func([]byte) error)
badger/badger.go:196:11: assignment mismatch: 2 variables but 1 values
badger/badger.go:196:24: not enough arguments in call to item.Value
        have ()
        want (func([]byte) error)
badger/badger.go:230:29: too many arguments in call to badgerTxn.Commit
        have (nil)
        want ()
```
* We can finally start compiling autocert, but there is a breaking change in certificates > 0.10.0  (https://github.com/smallstep/certificates/pull/80), which gives the error : 
```
./main.go:579:23: cannot use config.GetRootCAPath() (type string) as type []byte in argument to ca.NewProvisioner
./main.go:579:23: cannot use password (type []byte) as type ca.ClientOption in argument to ca.NewProvisioner
```
* After forcing certificates to 0.10.0 in Gopkg.toml, another breaking change, this time in cli > 0.10.0 (https://github.com/smallstep/cli/pull/131) : 
```
vendor/github.com/smallstep/certificates/authority/provisioner/jwk.go:145:16: assignment mismatch: 2 variables but 3 values
```
I could not get past this one, as I reach a dependency conflict if I try to force cli to 0.10.0:
```
Solving failure: No versions of github.com/smallstep/cli met constraints:
        v0.10.1: Could not introduce github.com/smallstep/cli@v0.10.1, as it has a dependency on github.com/smallstep/certificates with constraint master, which has no overlap with existing constraint ^0.10.0 from (root)
        v0.10.0: Could not introduce github.com/smallstep/cli@v0.10.0, as it has a dependency on github.com/smallstep/certificates with constraint master, which has no overlap with existing constraint ^0.10.0 from (root)
```

### Environment
```
# go version
go version go1.11.6 linux/amd64
```

### Steps to reproduce
```
git clone
cd autocert/controller
dep init
go build  -v  .
```
### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Additional context
Add any other context about the problem here

### PR DESCRIPTION
**Pull request by tooolbox**
### Description
Switches from using Dep to using Go Modules.  Will close #6 and possibly fix #8 

I am not a Make guru, but it seems like the Bootstrapping section isn't needed anymore.

Now, I also removed the linting stuff, but I can try to put it back using the `tools.go` pattern.  Any information that can be given on how the linting is supposed to work would be helpful.

### CODE REVIEW

**Comment by maraino** [comment]
Hi @tooolbox, thanks for doing this, right now I have a development version in my envrironment that was adding this and an extra feature, I want to release this soon. I'll make sure it builds with go modules.

**Comment by maraino** [comment]
That work is here https://github.com/smallstep/autocert/tree/cert-duration

**Comment by tooolbox** [comment]
Oh!  Sounds good then :)

**Comment by maraino** [comment]
I've created a PR from that branch, I'll try to release it next week.
https://github.com/smallstep/autocert/pull/13

**Pull request closed without merging**
