### PR TITLE
Add init-first annotation

### PR DESCRIPTION
**Pull request by tiagoposse**
This PR would allow for the definition and processing of the annotation "autocert.step.sm/init-first".
The use case for this is using Hashicorp Vault with TLS implementation based on autocert, where it's necessary to have the CA certificate added to the vault-agent-init init container.

The PR works by first adding a patch to remove all initContainers and afterwards re-adding all of them preceded by the bootstrapper.

I realise the implementation in this PR might not be optimal and I'm more than willing to implement it in a different way you might propose.

### CODE REVIEW

**Comment by maraino** [comment]
@tiagoposse the patch looks good, @mmalone do you have anything to say about the annotation name?

**Review by maraino — APPROVED** [review]
LGTM, and there's no extra feedback from @mmalone

**Comment by mmalone** [comment]
So this is just about the ordering of the init containers, right? Semantically, the new annotation is saying "make the autocert init container the first one to run instead of last"?

It looks like there's an additional change that: we're now volume mounting the certs into all of the init containers. That wasn't happening before, was it?

I'm ok with this as long as it's backwards compatible.

**Comment by tiagoposse** [comment]
It's not just about the ordering, mounting the certs into the other init containers was part of the goal, as this was the exact reason why I wanted it to init first. However, if this is something you don't want coupled, I can submit a PR to separate the behaviours :)

**Comment by mmalone** [comment]
Yea I figured as much. Pedantically I worry that this is _technically_ a security-sensitive change: random init containers that didn't have / don't need access to the cert & private key now get it. In this case, I understand that's exactly the point. And in practice, it probably doesn't matter. We're already mounting the private key into _all_ of your non-init containers.

There's a security/usability tradeoff here since any additional control would complicate the API... and it seems like people sort of treat everything in a pod as a unit. Also, without the `init-first` annotation, I'm pretty sure other init containers _won't_ actually get access to the cert since they'll run _before_ the cert has been generated. So I think we're good.

**Comment by tiagoposse** [comment]
That explanation is spot on.

The only way I can think of providing a limitation for this trade-off is to add an annotation such as "autocert.step.sm/inject-container-names: a,b" (and consequently inject-init-container-names) where you could specify the containers that get the volumeMount injected. This would mean the addition of an if statement when performing the injection.

As for the case without init-first, that's exactly what happens.

**Comment by mmalone** [comment]
Yea that's exactly what I was thinking. That's probably overkill though. And it's potentially fragile, as it depends on stable container names. So yea... I'm still kind of ambivalent. But working code wins, so unless you feel strongly I'm ok with accepting this PR as is.

Quick random question: you said you're using this for vault. Are these certs being used for peering by instances in a vault cluster (e.g., running the vault server in kubernetes) or are you issuing certificates to vault clients?

Thank you for your contribution!

**Comment by tiagoposse** [comment]
I think you raised a great point and it would make sense to improve upon this PR at a later stage. Although I agree it can be a fragile solution, in 99% of the cases the container name will be known or controllable and will not change in minor releases, so it doesn't seem impractical to have the option to do so. 

I'm provisioning the certificates used by vault servers (serving vault-0.vault.svc, vault-1.vault.svc and vault-1.vault.svc) and then inject the CA into each client.
Since the CA is not publicly trusted, vault agents in client pods need to use the annotation:
"vault.hashicorp.com/ca-cert: /var/run/autocert.step.cm/root.crt" in order to communicate with vault.

I eventually want to graduate this to use mTLS authentication between agents and vault. Annotations for this are already available, I just haven't had the time to test it all together

**Pull request merged**
